/**
 * Standardised error codes per FRD §4 & §5.
 * Every API error response includes one of these codes.
 */
export const ErrorCodes = {
  // Registration (FR-US-001..007)
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  WEAK_PASSWORD: 'WEAK_PASSWORD',

  // Verification (FR-US-008..012)
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_RESEND_LIMIT: 'OTP_RESEND_LIMIT',

  // Authentication (FR-US-013..020)
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  ACCOUNT_REJECTED: 'ACCOUNT_REJECTED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Profile (FR-US-021..027)
  IMMUTABLE_FIELD: 'IMMUTABLE_FIELD',
  CURRENT_PASSWORD_WRONG: 'CURRENT_PASSWORD_WRONG',
  PASSWORD_SAME_AS_OLD: 'PASSWORD_SAME_AS_OLD',
  PASSWORD_CONTAINS_PII: 'PASSWORD_CONTAINS_PII',

  // Travelers (FR-US-028..032)
  TRAVELER_LIMIT_EXCEEDED: 'TRAVELER_LIMIT_EXCEEDED',
  PRIMARY_TRAVELER_CANNOT_BE_DELETED: 'PRIMARY_TRAVELER_CANNOT_BE_DELETED',
  PRIMARY_TRAVELER_FLAG_IMMUTABLE: 'PRIMARY_TRAVELER_FLAG_IMMUTABLE',
  TRAVELER_NOT_FOUND: 'TRAVELER_NOT_FOUND',

  // Roles & Permissions (FR-US-033..039)
  ROLE_ALREADY_EXISTS: 'ROLE_ALREADY_EXISTS',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_TYPE_IMMUTABLE: 'ROLE_TYPE_IMMUTABLE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Audit (FR-US-040..044)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',

  // Markups
  MARKUP_NOT_FOUND: 'MARKUP_NOT_FOUND',
  MARKUP_ALREADY_EXISTS: 'MARKUP_ALREADY_EXISTS',

  // Banners
  BANNER_NOT_FOUND: 'BANNER_NOT_FOUND',
  BANNER_ALREADY_EXISTS: 'BANNER_ALREADY_EXISTS',

  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
